framework:
  rate_limiter:
    login:
      policy: 'fixed_window'
      limit: 2
      interval: '1 minutes'
    jwt_generation:
      policy: 'fixed_window'
      limit: 2
      interval: '5 minutes'
    authenticated_api:
      policy: 'fixed_window'
      limit: 500
      interval: '60 minutes'